### ISSUE TITLE
The novelty

### ISSUE THREAD

**Issue by hongxuchen** [crange/crange#1]
Hi @gnurag , thanks for the great tool.

However I'm wondering the novelty of `crange`: how is it different from other indexers such as [rtags](https://github.com/Andersbakken/rtags/), [clang-ctags](https://github.com/drothlis/clang-ctags) and [clang-tags](https://github.com/ffevotte/clang-tags)?

**Comment by gnurag** [comment]
Hello @HongxuChen, thanks for your feedback.

I originally developed Crange to help me with an internal project. Existing tools like clang-ctags  focus on replacing/enhancing ctags and export their data in ctags/etags file format. I wanted a tool that worked as fast and neatly as GNU Global and was capable of converting the entire TranslationUnit into searchable tokens in a database of some sort.

With Crange, I wanted to go a step beyond indexing tags and focus on indexing literally ecerything in the Translation Unit, including identifiers, statements, expressions, types, operators, literals and their source-range. I believe that the tools that focus on ctags compatibility lose out on these data points. I didn't actually try out rtags, but it is very close to the kind of data I wanted to harvest.

'crange', the command for querying crange database is barebones as of now. I intend to add command line options for querying by identifier type, expressions, literals, show statement body etc.

In the end, the real reason I didn't fork existing projects is because I wanted to play with rich metadata exposed by clang's TU nodes and try out my hands at python's multiprocessing library.

Anurag

**Comment by gnurag** [comment]
On a related note, I'm guilty of proliferation :)

![](http://imgs.xkcd.com/comics/standards.png)

**Comment by hongxuchen** [comment]
Thanks for your kind reply. And sorry I didn't realize what you mean in the
comics in the README page at first:-)
Seems a nice tool and maybe I'll try a few days later.

Thanks and Regards,
Hongxu

**Comment by gnurag** [comment]
You're welcome, and thanks again for your feedback.

**Comment by code-grep** [comment]
Hi guys, 
Cool tool indeed!

You can also try out our online tool here: 

https://code-grep.com

We are considering to try out crange and integrate into our backend of code-grep.com.
What do you think ?

**Comment by gnurag** [comment]
Hello code-grep,

code-grep looks quite interesting. what tool are you guys using at the moment for code extraction & analysis?

Anurag

**Comment by code-grep** [comment]
We use a slightly modified combination of ctags and gtags. At the moment we are trying to improve to make it much faster.

code-grep.com Team
